### ISSUE TITLE
Patch for /trunk/SimplexNoise/Noise.cs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [WardBenjamin/SimplexNoise#5]
```
If you use for example
x = -0.170068026f;
y = -0.05668934f;

You'll get negative indices, so it should be wrapped around with Mod.
```

Original issue reported on code.google.com by `karim.lu...@gmail.com` on 25 Jan 2015 at 9:43

Attachments:
- [Noise.cs.patch](https://storage.googleapis.com/google-code-attachments/simplexnoise/issue-5/comment-0/Noise.cs.patch)

**Comment by WardBenjamin** [comment]
This is easy enough to implement yourself if you need it, and is not a core feature. Closing,
