### ISSUE TITLE
API methods is not accessible in public

### ISSUE THREAD

**Issue by EmpireWorld** [WardBenjamin/SimplexNoise#6]
The APIs listed in the page is not accessible by public.

Here is the methods:

```csharp
Simplex.Noise.CalcPixel1D
Simplex.Noise.CalcPixel2D
Simplex.Noise.CalcPixel3D
```

i have checked the source code and you don't added public modifier.

**EDIT**: Also you don't added `static` modifier.

**Comment by WardBenjamin** [comment]
Fixed, thanks!
